client/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'client'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^new/$', views.new, name='new'),
    url(r'^existing/$', views.existing, name='existing'),
    url(r'^del_client/$', views.del_client, name='del_client'),

    # Operations
    url(r'^ls/$', views.ls, name='ls'),
    url(r'^mkdir/$', views.mkdir, name='mkdir'),
    url(r'^rmr/$', views.rmr, name='rmr'),
    url(r'^touchz/$', views.touchz, name='touchz'),
    url(r'^rm/$', views.rm, name='rm'),
    url(r'^put/$', views.put, name='put'),
    url(r'^moveFromLocal/$', views.moveFromLocal, name='moveFromLocal'),
    url(r'^cat/$', views.cat, name='cat'),
    url(r'^chown/$', views.chown, name='chown'),
    url(r'^count/$', views.count, name='count'),
    url(r'^clear_all/$', views.clear_all, name='clear_all'),

]

hadoop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('basic.urls')),
    url(r'^docker/', include('docker.urls') ),
    url(r'^vm/', include('vm.urls') ),
    url(r'^twitter/', include('twitter.urls') ),
    url(r'^client/', include('client.urls') ),

]


if settings.DEBUG:
	urlpatterns+= ( static(settings.STATIC_URL) )

vm/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'vm'

urlpatterns = [
    url(r'^version/$', views.version, name='version'),

    # VM hadoop version1
    url(r'^hadoopv1/$', views.hadoopv1, name='hadoopv1'),
    url(r'^posthadoopv1/$', views.posthadoopv1, name='posthadoopv1'),
    url(r'^loading_hv1/$', views.loading_hv1, name='loading_hv1'),
    url(r'^hv1_playbook/$', views.hv1_playbook, name='hv1_playbook'),
    
    # VM hadoop version2
    url(r'^hadoopv2/$', views.hadoopv2, name='hadoopv2'),
    url(r'^posthadoopv2/$', views.posthadoopv2, name='posthadoopv2'),
    url(r'^loading_hv2/$', views.loading_hv2, name='loading_hv2'),
    url(r'^hv2_playbook/$', views.hv2_playbook, name='hv2_playbook'),
    # Cluster Clear
    url(r'^clear_cluster/$', views.clear_cluster, name='clear_cluster'),
]

client/models.py
from django.db import models

# Create your models here.

client/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.views.generic import View
from django.template import loader
from django.http import HttpResponse
from django.core.urlresolvers import reverse
# Create your views here.
import mysql.connector as pysql
import subprocess as sb
import sys,os,time

def index (request):
	client = request.session.get('client')
	print (client)
	no_cluster = request.session.get('no_cluster')
	print(no_cluster)
	if (no_cluster=='No Cluster'):
		return render (request,'client/client.html',{'no_cluster':no_cluster})
	elif (client==None):
		cluster_existed = 'cluster_existed'
		return render (request,'client/client.html',{'cluster_existed':cluster_existed})
	elif (client=='created'):
		return redirect ('/client/home/')

def existing (request):
	request.session['client_name'] = 'container_2'
	request.session['client_id'] = sb.getoutput('sudo docker exec container_2 hostname')
	request.session['client_ip'] = sb.getoutput('sudo docker exec container_2 hostname -i')
	request.session['client'] = 'created'
	return redirect ('/client/home/')

def new (request):
	os.system (' sudo docker run -itd --privileged --restart always --name client hadoopv1.2')
	os.system (' sudo docker cp /root/docker_hv1/core-site.xml client:/etc/hadoop/core-site.xml')
	request.session['client_name'] = 'client'
	request.session['client_id'] = sb.getoutput('sudo docker exec client hostname')
	request.session['client_ip'] = sb.getoutput('sudo docker exec client hostname -i')
	request.session['client'] = 'created'
	return redirect ('/client/home/')

def home (request):
	client_name = request.session.get('client_name') 
	client_ip = request.session.get('client_ip') 
	client_id = request.session.get('client_id') 
	command = request.session.get('command') 
	request.session['command'] = None
	return render (request,'client/home.html',{
		'client_name':client_name,
		'client_ip':client_ip,
		'client_id':client_id,
		'command':command           })

def del_client (request):
	os.system('docker kill client')
	os.system('docker rm client')
	request.session['client_name'] = None
	request.session['client_id'] = None
	request.session['client_ip'] = None
	request.session['client'] = None
	return redirect ('/client/')

def ls (request):
	client_name = request.session.get('client_name')
	command = sb.getoutput('docker exec '+client_name+' hadoop fs -ls /')
	request.session['command'] = command
	return redirect ('/client/')

def cat (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	command = sb.getoutput('docker exec '+client_name+' hadoop fs -cat '+location)
	request.session['command'] = command
	return redirect ('/client/')

def mkdir (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -mkdir '+location)
	return redirect ('/client/')

def rmr (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -rmr '+location)
	return redirect ('/client/')

def touchz (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -touchz '+location)
	return redirect ('/client/')

def rm (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -rm '+location)
	return redirect ('/client/')

def clear_all (request):
	client_name = request.session.get('client_name')
	all_files = sb.getoutput('docker exec '+ client_name + ' hadoop fs -ls / | cut -d "/" -f2 | grep -vi Found')
	directories = all_files.split()
	print(directories)
	for files in directories:
		print ('cleaning /'+files+' ...')
		sb.getoutput ('docker exec '+ client_name + ' hadoop fs -rmr /'+files)
	return redirect ('/client/')

def put (request):
	location_from = request.POST.get('location_from')
	location_to = request.POST.get('location_to')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -put '+location_from+ ' '+location_to)
	return redirect ('/client/')

def moveFromLocal (request):
	location_from = request.POST.get('location_from')
	location_to = request.POST.get('location_to')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -moveFromLocal '+location_from+' '+location_to)
	return redirect ('/client/')

def chown (request):
	user = request.POST.get('user')
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	sb.getoutput('docker exec '+client_name+' hadoop fs -chown '+user+ ' '+location)
	return redirect ('/client/')

def count (request):
	location = request.POST.get('location')
	client_name = request.session.get('client_name')
	command = sb.getoutput('docker exec '+client_name+' hadoop fs -count '+location)
	request.session['command'] = command
	return redirect ('/client/')

templates/client/client.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Client {% endblock %}
{% block HDFSactive %} active {% endblock %}
{% block Clientactive %} active {% endblock %}

<!-- // styles // -->
{% block style %}  
.link{
	color: #595959 ;
	text-decoration:none;
}
.link:hover{
	color:blue
}
.img{
	position:fixed;
	bottom:80px;
	right:55px;
	opacity:0.6;
}
{% endblock %}


<!-- // body // -->
{% block body %}

{% if no_cluster %}

<center><h1 class="title mt-5"> No cluster is currently running... </h1></center>
<center><h1 class="title mt-5"> Create a cluster first. </h1></center>
<img src="{% static 'img/empty.png' %}" class="img-fluid img" height="400px" width="400px">

{% endif %}


{% if cluster_existed %}
<div class="main m-5">
<h1 class="title p-3"><a href="{% url 'client:new' %}" class="link">
	<i class="fa fa-plus-square-o" aria-hidden="true"></i> Create a new hadoop client </a>
</h1>
<hr>
<h1 class="title p-3"><a href="{% url 'client:existing' %}" class="link"
	><i class="fa fa-briefcase" aria-hidden="true"></i> Make existing node a client </a>
</h1>
</div>

<div class="img img-fluid">
	<img src="{% static 'img/client.png' %}" height="400px">
</div>
{% endif %}

{% endblock %}

templates/client/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Client {% endblock %}
{% block HDFSactive %} active {% endblock %}
{% block Clientactive %} active {% endblock %}

<!-- // styles // -->
{% block style %}  
.info{
	font-size:130%;
	padding:5px;
	margin:10px;
}
.del{
	color:red;
	cursor:pointer;
}
.main{
	margin:5px;
}
.op{
	color:blue
}
{% endblock %}


<!-- // body // -->
{% block body %}

<div class="row align-items-center">
	<h2 class="title col-5">Hadoop Client Operations</h2>
	<div class="offset-1 col-2 btn btn-info" data-toggle="modal" data-target="#clientinfo" >Client Info</div>
	<div class="offset-1 col-2 btn btn-danger" data-toggle="modal" data-target="#delclient" >Delete Client</div>
</div><hr>
<div class="main">
	<div class="op row">
	  <a href="{% url 'client:ls' %}" class="col-2"><i class="fa fa-list-alt" aria-hidden="true"></i> List directories</a>
			<div class="col-1"> ( ls )</div>
	  <a href="{% url 'client:clear_all' %}" class="col-3"><i class="fa fa-trash-o text-danger" aria-hidden="true"> Clear whole cluster data</i> </a>
	</div><hr>
	<div class="op">
		<form action="{% url 'client:cat' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-book" aria-hidden="true"></i> Read file</label>
			<div class="col-1"> ( cat )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="View">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:count' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-hand-peace-o" aria-hidden="true"></i> Count from files</label>
			<div class="col-1"> ( count )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Count">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:mkdir' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-plus-circle" aria-hidden="true"></i> Create a directory</label>
			<div class="col-1"> ( mkdir )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Create">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:rmr' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-minus-circle" aria-hidden="true"></i> Remove a directory</label>
			<div class="col-1"> ( rmr )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Remove">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:touchz' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-plus-square-o" aria-hidden="true"></i> Create a file</label>
			<div class="col-1"> ( touchz )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Create">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:rm' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-minus-square-o" aria-hidden="true"></i> Remove a file</label>
			<div class="col-1"> ( rm )</div>
			<input class="col-6" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Remove">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:put' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-upload" aria-hidden="true"></i> Copy from Local</label>
			<div class="col-1"> ( put )</div>
			<input class="col-3" name="location_from" placeholder='/from local'>
			<input class="col-3" name="location_to" placeholder='/to cluster'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Upload">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:moveFromLocal' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-scissors" aria-hidden="true"></i> Move from Local</label>
			<div class="col-1"> ( move )</div>
			<input class="col-3" name="location_from" placeholder='/from local'>
			<input class="col-3" name="location_to" placeholder='/to cluster'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Move">
	    </form><hr>
	</div>
	<div class="op">
		<form action="{% url 'client:chown' %}" method="POST" class="row align-items-center">
			{% csrf_token %}
			<label class="col-2" href=""><i class="fa fa-user" aria-hidden="true"></i> Change owenership</label>
			<div class="col-1"> ( chown )</div>
			<input class="col-3" name="user" placeholder='username'>
			<input class="col-3" name="location" placeholder='/path'>
			<input class="btn btn-sm  offset-1 col-1" type="submit" value="Change">
	    </form><hr>
	</div>
</div>


{% if command %}
<div id="myModal" class="modal fade">
    <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="background-color: #1a90ff;color:white">
	        <h4 class="modal-title">Output</h4>
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	    </div>
        <div class="modal-body p-3"><pre>
		{{ command }}
        </pre></div>
    </div>
</div>
{% endif %}


<!-- Clear Modal -->
<div class="modal fade" id="delclient" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Client</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">You are about to delete the existing client.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{% url 'client:del_client' %}">Confirm</a>
      </div>
    </div>
  </div>
</div>



<!-- Info -->
<div class="modal fade" id="clientinfo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Client Info</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body title info row">
      	<div class="col-6">Container name</div>
      	<div class="col-6">{{client_name}}</div>
      	<div class="col-6">Client IP</div>
      	<div class="col-6">{{client_ip}}</div>
      	<div class="col-6">Container ID</div>
      	<div class="col-6">{{client_id}}</div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#myModal").modal('show');
    });
</script>
{% endblock %}