basic/urls.py
from django.conf.urls import url , include
from . import views
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


app_name = 'basic'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^postsignup/$', views.postsignup, name='postsignup'),
    url(r'^postsignin/$', views.postsignin, name='postsignin'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^service_status/$', views.service_status, name='service_status'),
    url(r'^about/$', views.about, name='about'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^create/$', views.create, name='create'),
    
    # Dashboard


]

cluster/urls.py
from django.conf.urls import url , include
from . import views
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


app_name = 'cluster'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^postsignup/$', views.postsignup, name='postsignup'),
    url(r'^postsignin/$', views.postsignin, name='postsignin'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^service_status/$', views.service_status, name='service_status'),
    url(r'^about/$', views.about, name='about'),
    url(r'^settings/$', views.settings, name='settings'),
    
    # Dashboard
    url(r'^clear_cluster/$', views.clear_cluster, name='clear_cluster'),

]

docker/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'docker'

urlpatterns = [
    url(r'^version/$', views.version, name='version'),

    # Docker hadoop version1
    url(r'^hadoopv1/$', views.hadoopv1, name='hadoopv1'),
    url(r'^posthadoopv1/$', views.posthadoopv1, name='posthadoopv1'),
    url(r'^hv1_playbook/$', views.hv1_playbook, name='hv1_playbook'),
   
    # Docker hadoop version2
    url(r'^hadoopv2/$', views.hadoopv2, name='hadoopv2'),
    url(r'^posthadoopv2/$', views.posthadoopv2, name='posthadoopv2'),
    url(r'^hv2_playbook/$', views.hv2_playbook, name='hv2_playbook'),

    # Cluster Clear
    url(r'^clear_cluster/$', views.clear_cluster, name='clear_cluster'),

]

hadoop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('basic.urls')),
    url(r'^docker/', include('docker.urls') ),
    url(r'^vm/', include('vm.urls') ),
    url(r'^twitter/', include('twitter.urls') ),
    url(r'^client/', include('client.urls') ),

]


if settings.DEBUG:
	urlpatterns+= ( static(settings.STATIC_URL) )

twitter/urls.py
from django.conf.urls import url , include
from . import views
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


app_name = 'twitter'

urlpatterns = [
    url(r'^$', views.twitter, name='twitter'),
    url(r'^analyse/$', views.analyse, name='analyse'),


]

vm/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'vm'

urlpatterns = [
    url(r'^version/$', views.version, name='version'),

    # VM hadoop version1
    url(r'^hadoopv1/$', views.hadoopv1, name='hadoopv1'),
    url(r'^posthadoopv1/$', views.posthadoopv1, name='posthadoopv1'),
    url(r'^loading_hv1/$', views.loading_hv1, name='loading_hv1'),
    url(r'^hv1_playbook/$', views.hv1_playbook, name='hv1_playbook'),
    
    # VM hadoop version2
    url(r'^hadoopv2/$', views.hadoopv2, name='hadoopv2'),
    url(r'^posthadoopv2/$', views.posthadoopv2, name='posthadoopv2'),
    url(r'^loading_hv2/$', views.loading_hv2, name='loading_hv2'),
    url(r'^hv2_playbook/$', views.hv2_playbook, name='hv2_playbook'),
    # Cluster Clear
    url(r'^clear_cluster/$', views.clear_cluster, name='clear_cluster'),
]

twitter/forms.py
from django import forms

class userinput(forms.Form):
    q=forms.CharField(required=True,max_length=25,label='Input #hashtag')

twitter/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.views.generic import View
from .forms import userinput
from django.template import loader
from django.http import HttpResponse
# extra
import tweepy
from TwitterAPI import TwitterAPI
import urllib
from textblob import TextBlob
from tweepy.streaming import json
import pyrebase
from django.http import HttpResponseRedirect

from .sentimeter import primary

def twitter (request):
    user_input = userinput()
    return render(request, "twitter.html")

def analyse(request):
    user_input = request.GET['hash']
    no_of_tweets = int(request.GET['no_of_tweets'])
    print (user_input)
    print (no_of_tweets)
    data = primary(user_input,no_of_tweets)
    return render(request, "result.html", {'data': data})

templates/dochv1_playbook.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Loading... {% endblock %}

{% block header %}  
    <script language="JavaScript" type="text/javascript">
window.setTimeout(function(){

    // Move to a new location or you can do something else
    window.location.href = "{% url 'basic:dashboard' %}";

}, 30000);
    </script>

{% endblock %}

{% block Sercivesactive %} active {% endblock %}

<!-- // styles // -->
{% block style %}  
.loader{
    width: 250px;
    height: 250px;
    position: relative;
    margin: 40px auto;
}
.loader > div{
    background: transparent;
    border: 4px solid transparent;
    border-color: transparent transparent transparent #152861;
    -webkit-border-radius: 100%;
    -moz-border-radius: 100%;
    border-radius: 100%;
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translate"("-50%, -50%")";
    -moz-transform: translate"("-50%, -50%")";
    -ms-transform: translate"("-50%, -50%")";
    -o-transform: translate"("-50%, -50%")";
    transform: translate"("-50%, -50%")";
    -webkit-transform: translate(-50%, -50%) rotate(0);
    -moz-transform: translate(-50%, -50%) rotate(0);
    -ms-transform: translate(-50%, -50%) rotate(0);
    -o-transform: translate(-50%, -50%) rotate(0);
    transform: translate(-50%, -50%) rotate(0);
    -webkit-animation: loading 2s infinite ease-in-out;
    -moz-animation: loading 2s infinite ease-in-out;
    -o-animation: loading 2s infinite ease-in-out;
    animation: loading 2s infinite ease-in-out;
}
.loader .loader-inner-1{
    width: 20px;
    height: 20px;
    -webkit-animation-delay: 0.1s;
    -moz-animation-delay: 0.1s;
    -o-animation-delay: 0.1s;
    animation-delay: 0.1s;
}
.loader .loader-inner-2{
    width: 25px;
    height: 25px;
    -webkit-animation-delay: 0.2s;
    -moz-animation-delay: 0.2s;
    -o-animation-delay: 0.2s;
    animation-delay: 0.2s;
}
.loader .loader-inner-3{
    width: 30px;
    height: 30px;
    -webkit-animation-delay: 0.3s;
    -moz-animation-delay: 0.3s;
    -o-animation-delay: 0.3s;
    animation-delay: 0.3s;
}
.loader .loader-inner-4{
    width: 35px;
    height: 35px;
    -webkit-animation-delay: 0.4s;
    -moz-animation-delay: 0.4s;
    -o-animation-delay: 0.4s;
    animation-delay: 0.4s;
}
.loader .loader-inner-5{
    width: 40px;
    height: 40px;
    -webkit-animation-delay: 0.5s;
    -moz-animation-delay: 0.5s;
    -o-animation-delay: 0.5s;
    animation-delay: 0.5s;
}
.loader .loader-inner-6{
    width: 45px;
    height: 45px;
    -webkit-animation-delay: 0.6s;
    -moz-animation-delay: 0.6s;
    -o-animation-delay: 0.6s;
    animation-delay: 0.6s;
}
.loader .loader-inner-7{
    width: 50px;
    height: 50px;
    -webkit-animation-delay: 0.7s;
    -moz-animation-delay: 0.7s;
    -o-animation-delay: 0.7s;
    animation-delay: 0.7s;
}
.loader .loader-inner-8{
    width: 55px;
    height: 55px;
    -webkit-animation-delay: 0.8s;
    -moz-animation-delay: 0.8s;
    -o-animation-delay: 0.8s;
    animation-delay: 0.8s;
}
.loader .loader-inner-9{
    width: 60px;
    height: 60px;
    -webkit-animation-delay: 0.9s;
    -moz-animation-delay: 0.9s;
    -o-animation-delay: 0.9s;
    animation-delay: 0.9s;
}
.loader .loader-inner-10{
    width: 65px;
    height: 65px;
    -webkit-animation-delay: 1s;
    -moz-animation-delay: 1s;
    -o-animation-delay: 1s;
    animation-delay: 1s;
}
@-webkit-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@-moz-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@-o-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color:#FFFA6B transparent transparent #DD480C;
    }
}	
{% endblock %}

<!-- // body // -->
{% block body %}
	
<meta http-equiv='refresh' content="0;{% url 'docker:hv1_playbook' %}">
	

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="loader">
                <div class="loader-inner-1"></div>
                <div class="loader-inner-2"></div>
                <div class="loader-inner-3"></div>
                <div class="loader-inner-4"></div>
                <div class="loader-inner-5"></div>
                <div class="loader-inner-6"></div>
                <div class="loader-inner-7"></div>
                <div class="loader-inner-8"></div>
                <div class="loader-inner-9"></div>
                <div class="loader-inner-10"></div>
            </div>
        </div>
    </div>
</div>

	<center><h1 class="title"> Ansible playbook is running ... </h1></center>

{% endblock %}

templates/dochv2_playbook.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Loading... {% endblock %}

{% block header %}  
    <script language="JavaScript" type="text/javascript">
window.setTimeout(function(){

    // Move to a new location or you can do something else
    window.location.href = "{% url 'basic:dashboard' %}";

}, 20000);
    </script>

{% endblock %}

{% block Sercivesactive %} active {% endblock %}

<!-- // styles // -->
{% block style %}  
.loader{
    width: 250px;
    height: 250px;
    position: relative;
    margin: 40px auto;
}
.loader > div{
    background: transparent;
    border: 4px solid transparent;
    border-color: transparent transparent transparent #152861;
    -webkit-border-radius: 100%;
    -moz-border-radius: 100%;
    border-radius: 100%;
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translate"("-50%, -50%")";
    -moz-transform: translate"("-50%, -50%")";
    -ms-transform: translate"("-50%, -50%")";
    -o-transform: translate"("-50%, -50%")";
    transform: translate"("-50%, -50%")";
    -webkit-transform: translate(-50%, -50%) rotate(0);
    -moz-transform: translate(-50%, -50%) rotate(0);
    -ms-transform: translate(-50%, -50%) rotate(0);
    -o-transform: translate(-50%, -50%) rotate(0);
    transform: translate(-50%, -50%) rotate(0);
    -webkit-animation: loading 2s infinite ease-in-out;
    -moz-animation: loading 2s infinite ease-in-out;
    -o-animation: loading 2s infinite ease-in-out;
    animation: loading 2s infinite ease-in-out;
}
.loader .loader-inner-1{
    width: 20px;
    height: 20px;
    -webkit-animation-delay: 0.1s;
    -moz-animation-delay: 0.1s;
    -o-animation-delay: 0.1s;
    animation-delay: 0.1s;
}
.loader .loader-inner-2{
    width: 25px;
    height: 25px;
    -webkit-animation-delay: 0.2s;
    -moz-animation-delay: 0.2s;
    -o-animation-delay: 0.2s;
    animation-delay: 0.2s;
}
.loader .loader-inner-3{
    width: 30px;
    height: 30px;
    -webkit-animation-delay: 0.3s;
    -moz-animation-delay: 0.3s;
    -o-animation-delay: 0.3s;
    animation-delay: 0.3s;
}
.loader .loader-inner-4{
    width: 35px;
    height: 35px;
    -webkit-animation-delay: 0.4s;
    -moz-animation-delay: 0.4s;
    -o-animation-delay: 0.4s;
    animation-delay: 0.4s;
}
.loader .loader-inner-5{
    width: 40px;
    height: 40px;
    -webkit-animation-delay: 0.5s;
    -moz-animation-delay: 0.5s;
    -o-animation-delay: 0.5s;
    animation-delay: 0.5s;
}
.loader .loader-inner-6{
    width: 45px;
    height: 45px;
    -webkit-animation-delay: 0.6s;
    -moz-animation-delay: 0.6s;
    -o-animation-delay: 0.6s;
    animation-delay: 0.6s;
}
.loader .loader-inner-7{
    width: 50px;
    height: 50px;
    -webkit-animation-delay: 0.7s;
    -moz-animation-delay: 0.7s;
    -o-animation-delay: 0.7s;
    animation-delay: 0.7s;
}
.loader .loader-inner-8{
    width: 55px;
    height: 55px;
    -webkit-animation-delay: 0.8s;
    -moz-animation-delay: 0.8s;
    -o-animation-delay: 0.8s;
    animation-delay: 0.8s;
}
.loader .loader-inner-9{
    width: 60px;
    height: 60px;
    -webkit-animation-delay: 0.9s;
    -moz-animation-delay: 0.9s;
    -o-animation-delay: 0.9s;
    animation-delay: 0.9s;
}
.loader .loader-inner-10{
    width: 65px;
    height: 65px;
    -webkit-animation-delay: 1s;
    -moz-animation-delay: 1s;
    -o-animation-delay: 1s;
    animation-delay: 1s;
}
@-webkit-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@-moz-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@-o-keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color: #FFFA6B transparent transparent #DD480C;
    }
}
@keyframes loading{
    50% {
        -webkit-transform: translate(-50%, -50%) rotate(360deg);
        -moz-transform: translate(-50%, -50%) rotate(360deg);
        -ms-transform: translate(-50%, -50%) rotate(360deg);
        -o-transform: translate(-50%, -50%) rotate(360deg);
        transform: translate(-50%, -50%) rotate(360deg);
        border-color: transparent transparent #FFFA6B #DD480C;
    }
    75% {
        border-color:#FFFA6B transparent transparent #DD480C;
    }
}	
{% endblock %}

<!-- // body // -->
{% block body %}
	
<meta http-equiv='refresh' content="0;{% url 'docker:hv2_playbook' %}">
	

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="loader">
                <div class="loader-inner-1"></div>
                <div class="loader-inner-2"></div>
                <div class="loader-inner-3"></div>
                <div class="loader-inner-4"></div>
                <div class="loader-inner-5"></div>
                <div class="loader-inner-6"></div>
                <div class="loader-inner-7"></div>
                <div class="loader-inner-8"></div>
                <div class="loader-inner-9"></div>
                <div class="loader-inner-10"></div>
            </div>
        </div>
    </div>
</div>

	<center><h1 class="title"> Ansible playbook is running ... </h1></center>

{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>index page</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	 <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
	  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>

<style>
/*Vedio overlay*/
#myVideo {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;
    object-fit: fill;
    z-index: -100;
    opacity: 0.6;
}

.video-overlay {
    position: fixed;
    bottom: 0;
    background: rgba(127, 153, 152, 0.4117647058823529);
    width: 100%;
    height: 100%;
    z-index: -2;
}

.card-container.card {
    max-width: 750px;
    padding: 50px 50px;
}

.btn {
    font-weight: 700;
    cursor: pointer;
}

.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    border-radius: 10px;
    box-shadow: 0px 5px 5px rgba(0, 0, 0, 0.5);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    border-radius: 50%;
}

.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.reauth-email {
    display: block;
    color: #404040;
    line-height: 2;
    margin-bottom: 10px;
    font-size: 14px;
    text-align: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 4px;
    font-weight: 700;
    font-size: 16px;
    height: 38px;
    border-radius: 0px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color:#fc7a1a  ;
    color:white ;
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color:  #6e6965 ;
}
.signup{
    position: absolute;
    top: 10px;
    right: 30px;
    font-size: 120%;
    background-color:  #ff8000 ;
}
.signup:hover{
    background-color:  #e27100 
}
</style>


<body>

{% if message %}
<script type="text/javascript">
  alert ( '{{ message }}' );
</script>
{% endif %}

<!-- Vedio Overlay -->
<div class="video-overlay"></div>
<video id="myVideo" controls autoplay muted loop>
    <source src="{% static 'video/background.mp4' %}" type="video/mp4" />
</video> 
<!-- End Video Overlay -->

<div type="button" class="signup btn btn-md"><a href="{% url 'basic:signup' %}" style="color:white;text-decoration:none">Signup</a></div>

<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="{% static 'img/adhoc.jpg' %}" />
        <p id="profile-name" class="profile-name-card"></p>
        
        <form  action="{% url 'basic:postsignin' %}" class="form-signin" method="POST">
            {% csrf_token %}
            <span id="reauth-email" class="reauth-email"></span>
            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name="email" required autofocus>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>

            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
        </form><!-- /form -->

        <a href="#" class="forgot-password">
            Forgot the password?
        </a>
    </div><!-- /card-container -->
</div><!-- /container -->


</body>

</html>

templates/invalid.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Invalid Entries</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	 <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
</head>
<style type="text/css">
body{
	background: url("{% static 'img/invalid-password.jpg' %}") no-repeat;
}
.shift{
	font-family: Pacifico;
	position: absolute;
	top: 100px;
	left: 800px;
}
.btn{
	margin-top:100px;
	padding: 15px;
}
.btn:hover{
	background-color: grey;
}
.btn a:hover{
	color: black;
}
</style>
<body>
<h1 class="shift">Invalid email or password</h1>
<div class="btn btn-info btn-lg shift"><a href="{% url 'basic:index' %}" style="color: white">Try Again...</a></div>

</body>
</html>

templates/sample.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Dashboard {% endblock %}

<!-- // styles // -->
{% block style %}  

{% endblock %}

{% block Dashboardactive %} active {% endblock %}

<!-- // body // -->
{% block body %}


{% endblock %}